// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.0
// source: parcel/parcel.proto

package parcel

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ParcelService_CreateParcel_FullMethodName = "/parcel.ParcelService/CreateParcel"
	ParcelService_UpdateParcel_FullMethodName = "/parcel.ParcelService/UpdateParcel"
)

// ParcelServiceClient is the client API for ParcelService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ParcelServiceClient interface {
	CreateParcel(ctx context.Context, in *CreateParcelRequest, opts ...grpc.CallOption) (*CreateParcelResponse, error)
	UpdateParcel(ctx context.Context, in *UpdateParcelRequest, opts ...grpc.CallOption) (*UpdateParcelResponse, error)
}

type parcelServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewParcelServiceClient(cc grpc.ClientConnInterface) ParcelServiceClient {
	return &parcelServiceClient{cc}
}

func (c *parcelServiceClient) CreateParcel(ctx context.Context, in *CreateParcelRequest, opts ...grpc.CallOption) (*CreateParcelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateParcelResponse)
	err := c.cc.Invoke(ctx, ParcelService_CreateParcel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parcelServiceClient) UpdateParcel(ctx context.Context, in *UpdateParcelRequest, opts ...grpc.CallOption) (*UpdateParcelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateParcelResponse)
	err := c.cc.Invoke(ctx, ParcelService_UpdateParcel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ParcelServiceServer is the server API for ParcelService service.
// All implementations must embed UnimplementedParcelServiceServer
// for forward compatibility.
type ParcelServiceServer interface {
	CreateParcel(context.Context, *CreateParcelRequest) (*CreateParcelResponse, error)
	UpdateParcel(context.Context, *UpdateParcelRequest) (*UpdateParcelResponse, error)
	mustEmbedUnimplementedParcelServiceServer()
}

// UnimplementedParcelServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedParcelServiceServer struct{}

func (UnimplementedParcelServiceServer) CreateParcel(context.Context, *CreateParcelRequest) (*CreateParcelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateParcel not implemented")
}
func (UnimplementedParcelServiceServer) UpdateParcel(context.Context, *UpdateParcelRequest) (*UpdateParcelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateParcel not implemented")
}
func (UnimplementedParcelServiceServer) mustEmbedUnimplementedParcelServiceServer() {}
func (UnimplementedParcelServiceServer) testEmbeddedByValue()                       {}

// UnsafeParcelServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ParcelServiceServer will
// result in compilation errors.
type UnsafeParcelServiceServer interface {
	mustEmbedUnimplementedParcelServiceServer()
}

func RegisterParcelServiceServer(s grpc.ServiceRegistrar, srv ParcelServiceServer) {
	// If the following call panics, it indicates UnimplementedParcelServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ParcelService_ServiceDesc, srv)
}

func _ParcelService_CreateParcel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateParcelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParcelServiceServer).CreateParcel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParcelService_CreateParcel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParcelServiceServer).CreateParcel(ctx, req.(*CreateParcelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParcelService_UpdateParcel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateParcelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParcelServiceServer).UpdateParcel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParcelService_UpdateParcel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParcelServiceServer).UpdateParcel(ctx, req.(*UpdateParcelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ParcelService_ServiceDesc is the grpc.ServiceDesc for ParcelService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ParcelService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "parcel.ParcelService",
	HandlerType: (*ParcelServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateParcel",
			Handler:    _ParcelService_CreateParcel_Handler,
		},
		{
			MethodName: "UpdateParcel",
			Handler:    _ParcelService_UpdateParcel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "parcel/parcel.proto",
}
