// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: parcel/parcel.proto

package parcel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ParcelStatus int32

const (
	ParcelStatus_PARCEL_STATUS_UNSPECIFIED ParcelStatus = 0
	ParcelStatus_PARCEL_STATUS_CREATED     ParcelStatus = 1
	ParcelStatus_PARCEL_STATUS_PICKED_UP   ParcelStatus = 2
	ParcelStatus_PARCEL_STATUS_IN_TRANSIT  ParcelStatus = 3
	ParcelStatus_PARCEL_STATUS_DELIVERED   ParcelStatus = 4
	ParcelStatus_PARCEL_STATUS_CANCELLED   ParcelStatus = 5
)

// Enum value maps for ParcelStatus.
var (
	ParcelStatus_name = map[int32]string{
		0: "PARCEL_STATUS_UNSPECIFIED",
		1: "PARCEL_STATUS_CREATED",
		2: "PARCEL_STATUS_PICKED_UP",
		3: "PARCEL_STATUS_IN_TRANSIT",
		4: "PARCEL_STATUS_DELIVERED",
		5: "PARCEL_STATUS_CANCELLED",
	}
	ParcelStatus_value = map[string]int32{
		"PARCEL_STATUS_UNSPECIFIED": 0,
		"PARCEL_STATUS_CREATED":     1,
		"PARCEL_STATUS_PICKED_UP":   2,
		"PARCEL_STATUS_IN_TRANSIT":  3,
		"PARCEL_STATUS_DELIVERED":   4,
		"PARCEL_STATUS_CANCELLED":   5,
	}
)

func (x ParcelStatus) Enum() *ParcelStatus {
	p := new(ParcelStatus)
	*p = x
	return p
}

func (x ParcelStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ParcelStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_parcel_parcel_proto_enumTypes[0].Descriptor()
}

func (ParcelStatus) Type() protoreflect.EnumType {
	return &file_parcel_parcel_proto_enumTypes[0]
}

func (x ParcelStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ParcelStatus.Descriptor instead.
func (ParcelStatus) EnumDescriptor() ([]byte, []int) {
	return file_parcel_parcel_proto_rawDescGZIP(), []int{0}
}

type CreateParcelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateParcelRequest) Reset() {
	*x = CreateParcelRequest{}
	mi := &file_parcel_parcel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateParcelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateParcelRequest) ProtoMessage() {}

func (x *CreateParcelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parcel_parcel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateParcelRequest.ProtoReflect.Descriptor instead.
func (*CreateParcelRequest) Descriptor() ([]byte, []int) {
	return file_parcel_parcel_proto_rawDescGZIP(), []int{0}
}

func (x *CreateParcelRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CreateParcelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParcelId      string                 `protobuf:"bytes,1,opt,name=parcel_id,json=parcelId,proto3" json:"parcel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateParcelResponse) Reset() {
	*x = CreateParcelResponse{}
	mi := &file_parcel_parcel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateParcelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateParcelResponse) ProtoMessage() {}

func (x *CreateParcelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_parcel_parcel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateParcelResponse.ProtoReflect.Descriptor instead.
func (*CreateParcelResponse) Descriptor() ([]byte, []int) {
	return file_parcel_parcel_proto_rawDescGZIP(), []int{1}
}

func (x *CreateParcelResponse) GetParcelId() string {
	if x != nil {
		return x.ParcelId
	}
	return ""
}

type UpdateParcelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParcelId      string                 `protobuf:"bytes,1,opt,name=parcel_id,json=parcelId,proto3" json:"parcel_id,omitempty"`
	Address       *Address               `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Status        ParcelStatus           `protobuf:"varint,3,opt,name=status,proto3,enum=parcel.ParcelStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateParcelRequest) Reset() {
	*x = UpdateParcelRequest{}
	mi := &file_parcel_parcel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateParcelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateParcelRequest) ProtoMessage() {}

func (x *UpdateParcelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_parcel_parcel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateParcelRequest.ProtoReflect.Descriptor instead.
func (*UpdateParcelRequest) Descriptor() ([]byte, []int) {
	return file_parcel_parcel_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateParcelRequest) GetParcelId() string {
	if x != nil {
		return x.ParcelId
	}
	return ""
}

func (x *UpdateParcelRequest) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *UpdateParcelRequest) GetStatus() ParcelStatus {
	if x != nil {
		return x.Status
	}
	return ParcelStatus_PARCEL_STATUS_UNSPECIFIED
}

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AddressLine_1 string                 `protobuf:"bytes,1,opt,name=address_line_1,json=addressLine1,proto3" json:"address_line_1,omitempty"`
	AddressLine_2 string                 `protobuf:"bytes,2,opt,name=address_line_2,json=addressLine2,proto3" json:"address_line_2,omitempty"`
	City          string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	Country       string                 `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	PostalCode    string                 `protobuf:"bytes,6,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_parcel_parcel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_parcel_parcel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_parcel_parcel_proto_rawDescGZIP(), []int{3}
}

func (x *Address) GetAddressLine_1() string {
	if x != nil {
		return x.AddressLine_1
	}
	return ""
}

func (x *Address) GetAddressLine_2() string {
	if x != nil {
		return x.AddressLine_2
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Address) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Address) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

type UpdateParcelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParcelId      string                 `protobuf:"bytes,1,opt,name=parcel_id,json=parcelId,proto3" json:"parcel_id,omitempty"`
	Status        ParcelStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=parcel.ParcelStatus" json:"status,omitempty"`
	Address       *Address               `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateParcelResponse) Reset() {
	*x = UpdateParcelResponse{}
	mi := &file_parcel_parcel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateParcelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateParcelResponse) ProtoMessage() {}

func (x *UpdateParcelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_parcel_parcel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateParcelResponse.ProtoReflect.Descriptor instead.
func (*UpdateParcelResponse) Descriptor() ([]byte, []int) {
	return file_parcel_parcel_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateParcelResponse) GetParcelId() string {
	if x != nil {
		return x.ParcelId
	}
	return ""
}

func (x *UpdateParcelResponse) GetStatus() ParcelStatus {
	if x != nil {
		return x.Status
	}
	return ParcelStatus_PARCEL_STATUS_UNSPECIFIED
}

func (x *UpdateParcelResponse) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

var File_parcel_parcel_proto protoreflect.FileDescriptor

const file_parcel_parcel_proto_rawDesc = "" +
	"\n" +
	"\x13parcel/parcel.proto\x12\x06parcel\".\n" +
	"\x13CreateParcelRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"3\n" +
	"\x14CreateParcelResponse\x12\x1b\n" +
	"\tparcel_id\x18\x01 \x01(\tR\bparcelId\"\x8b\x01\n" +
	"\x13UpdateParcelRequest\x12\x1b\n" +
	"\tparcel_id\x18\x01 \x01(\tR\bparcelId\x12)\n" +
	"\aaddress\x18\x02 \x01(\v2\x0f.parcel.AddressR\aaddress\x12,\n" +
	"\x06status\x18\x03 \x01(\x0e2\x14.parcel.ParcelStatusR\x06status\"\xba\x01\n" +
	"\aAddress\x12$\n" +
	"\x0eaddress_line_1\x18\x01 \x01(\tR\faddressLine1\x12$\n" +
	"\x0eaddress_line_2\x18\x02 \x01(\tR\faddressLine2\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12\x18\n" +
	"\acountry\x18\x05 \x01(\tR\acountry\x12\x1f\n" +
	"\vpostal_code\x18\x06 \x01(\tR\n" +
	"postalCode\"\x8c\x01\n" +
	"\x14UpdateParcelResponse\x12\x1b\n" +
	"\tparcel_id\x18\x01 \x01(\tR\bparcelId\x12,\n" +
	"\x06status\x18\x02 \x01(\x0e2\x14.parcel.ParcelStatusR\x06status\x12)\n" +
	"\aaddress\x18\x03 \x01(\v2\x0f.parcel.AddressR\aaddress*\xbd\x01\n" +
	"\fParcelStatus\x12\x1d\n" +
	"\x19PARCEL_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15PARCEL_STATUS_CREATED\x10\x01\x12\x1b\n" +
	"\x17PARCEL_STATUS_PICKED_UP\x10\x02\x12\x1c\n" +
	"\x18PARCEL_STATUS_IN_TRANSIT\x10\x03\x12\x1b\n" +
	"\x17PARCEL_STATUS_DELIVERED\x10\x04\x12\x1b\n" +
	"\x17PARCEL_STATUS_CANCELLED\x10\x052\xa5\x01\n" +
	"\rParcelService\x12I\n" +
	"\fCreateParcel\x12\x1b.parcel.CreateParcelRequest\x1a\x1c.parcel.CreateParcelResponse\x12I\n" +
	"\fUpdateParcel\x12\x1b.parcel.UpdateParcelRequest\x1a\x1c.parcel.UpdateParcelResponseB,Z*github.com/sachinggsingh/PDTS-Go/pb/parcelb\x06proto3"

var (
	file_parcel_parcel_proto_rawDescOnce sync.Once
	file_parcel_parcel_proto_rawDescData []byte
)

func file_parcel_parcel_proto_rawDescGZIP() []byte {
	file_parcel_parcel_proto_rawDescOnce.Do(func() {
		file_parcel_parcel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_parcel_parcel_proto_rawDesc), len(file_parcel_parcel_proto_rawDesc)))
	})
	return file_parcel_parcel_proto_rawDescData
}

var file_parcel_parcel_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_parcel_parcel_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_parcel_parcel_proto_goTypes = []any{
	(ParcelStatus)(0),            // 0: parcel.ParcelStatus
	(*CreateParcelRequest)(nil),  // 1: parcel.CreateParcelRequest
	(*CreateParcelResponse)(nil), // 2: parcel.CreateParcelResponse
	(*UpdateParcelRequest)(nil),  // 3: parcel.UpdateParcelRequest
	(*Address)(nil),              // 4: parcel.Address
	(*UpdateParcelResponse)(nil), // 5: parcel.UpdateParcelResponse
}
var file_parcel_parcel_proto_depIdxs = []int32{
	4, // 0: parcel.UpdateParcelRequest.address:type_name -> parcel.Address
	0, // 1: parcel.UpdateParcelRequest.status:type_name -> parcel.ParcelStatus
	0, // 2: parcel.UpdateParcelResponse.status:type_name -> parcel.ParcelStatus
	4, // 3: parcel.UpdateParcelResponse.address:type_name -> parcel.Address
	1, // 4: parcel.ParcelService.CreateParcel:input_type -> parcel.CreateParcelRequest
	3, // 5: parcel.ParcelService.UpdateParcel:input_type -> parcel.UpdateParcelRequest
	2, // 6: parcel.ParcelService.CreateParcel:output_type -> parcel.CreateParcelResponse
	5, // 7: parcel.ParcelService.UpdateParcel:output_type -> parcel.UpdateParcelResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_parcel_parcel_proto_init() }
func file_parcel_parcel_proto_init() {
	if File_parcel_parcel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_parcel_parcel_proto_rawDesc), len(file_parcel_parcel_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_parcel_parcel_proto_goTypes,
		DependencyIndexes: file_parcel_parcel_proto_depIdxs,
		EnumInfos:         file_parcel_parcel_proto_enumTypes,
		MessageInfos:      file_parcel_parcel_proto_msgTypes,
	}.Build()
	File_parcel_parcel_proto = out.File
	file_parcel_parcel_proto_goTypes = nil
	file_parcel_parcel_proto_depIdxs = nil
}
