apiVersion: v1
kind: ConfigMap
metadata:
  name: pdts-config
data:
  # General
  PORT: "8080"
  
  # Service URLs (internal K8s DNS)
  AUTH_SERVICE_URL: "http://auth-service:8081"
  USER_SERVICE_URL: "http://user-service:8084"
  PARCEL_SERVICE_URL: "http://parcel-service:8082"
  TRACKING_SERVICE_URL: "http://tracking-service:8083"
  
  # MongoDB
  MONGODB_URI: "mongodb://admin:admin123@mongodb:27017/parcel_db?authSource=admin"
  MONGODB_DATABASE_AUTH: "auth-service"
  MONGODB_DATABASE_PARCEL: "parcel-service"
  MONGODB_DATABASE_TRACKING: "tracking"
  MONGODB_DATABASE_USER: "address-service"
  
  # Kafka
  KAFKA_BROKERS: "kafka:9092"
  
  # OAuth
  GITHUB_REDIRECT_URL: "" // Add your GitHub OAuth Redirect URL here
