apiVersion: v1
kind: Secret
metadata:
  name: pdts-secrets
type: Opaque
stringData:
  JWT_SECRET: "" // Add your JWT secret here
  GITHUB_CLIENT_ID: "" // Add your GitHub Client ID here
  GITHUB_CLIENT_SECRET: "" // Add your GitHub Client Secret here
  OAUTH_STATE_SECRET: "" // Add your OAuth State Secret here
  MONGO_ROOT_PASSWORD: "" // Add your MongoDB root password here
