// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: tracking/tracking.proto

package tracking

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTrackingDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParcelId      string                 `protobuf:"bytes,1,opt,name=parcel_id,json=parcelId,proto3" json:"parcel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrackingDetailsRequest) Reset() {
	*x = GetTrackingDetailsRequest{}
	mi := &file_tracking_tracking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrackingDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrackingDetailsRequest) ProtoMessage() {}

func (x *GetTrackingDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tracking_tracking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrackingDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetTrackingDetailsRequest) Descriptor() ([]byte, []int) {
	return file_tracking_tracking_proto_rawDescGZIP(), []int{0}
}

func (x *GetTrackingDetailsRequest) GetParcelId() string {
	if x != nil {
		return x.ParcelId
	}
	return ""
}

type GetTrackingDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParcelId      string                 `protobuf:"bytes,1,opt,name=parcel_id,json=parcelId,proto3" json:"parcel_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	History       []string               `protobuf:"bytes,3,rep,name=history,proto3" json:"history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrackingDetailsResponse) Reset() {
	*x = GetTrackingDetailsResponse{}
	mi := &file_tracking_tracking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrackingDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrackingDetailsResponse) ProtoMessage() {}

func (x *GetTrackingDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tracking_tracking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrackingDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetTrackingDetailsResponse) Descriptor() ([]byte, []int) {
	return file_tracking_tracking_proto_rawDescGZIP(), []int{1}
}

func (x *GetTrackingDetailsResponse) GetParcelId() string {
	if x != nil {
		return x.ParcelId
	}
	return ""
}

func (x *GetTrackingDetailsResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetTrackingDetailsResponse) GetHistory() []string {
	if x != nil {
		return x.History
	}
	return nil
}

var File_tracking_tracking_proto protoreflect.FileDescriptor

const file_tracking_tracking_proto_rawDesc = "" +
	"\n" +
	"\x17tracking/tracking.proto\x12\btracking\"8\n" +
	"\x19GetTrackingDetailsRequest\x12\x1b\n" +
	"\tparcel_id\x18\x01 \x01(\tR\bparcelId\"k\n" +
	"\x1aGetTrackingDetailsResponse\x12\x1b\n" +
	"\tparcel_id\x18\x01 \x01(\tR\bparcelId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\ahistory\x18\x03 \x03(\tR\ahistory2r\n" +
	"\x0fTrackingService\x12_\n" +
	"\x12GetTrackingDetails\x12#.tracking.GetTrackingDetailsRequest\x1a$.tracking.GetTrackingDetailsResponseB.Z,github.com/sachinggsingh/PDTS-Go/pb/trackingb\x06proto3"

var (
	file_tracking_tracking_proto_rawDescOnce sync.Once
	file_tracking_tracking_proto_rawDescData []byte
)

func file_tracking_tracking_proto_rawDescGZIP() []byte {
	file_tracking_tracking_proto_rawDescOnce.Do(func() {
		file_tracking_tracking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tracking_tracking_proto_rawDesc), len(file_tracking_tracking_proto_rawDesc)))
	})
	return file_tracking_tracking_proto_rawDescData
}

var file_tracking_tracking_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tracking_tracking_proto_goTypes = []any{
	(*GetTrackingDetailsRequest)(nil),  // 0: tracking.GetTrackingDetailsRequest
	(*GetTrackingDetailsResponse)(nil), // 1: tracking.GetTrackingDetailsResponse
}
var file_tracking_tracking_proto_depIdxs = []int32{
	0, // 0: tracking.TrackingService.GetTrackingDetails:input_type -> tracking.GetTrackingDetailsRequest
	1, // 1: tracking.TrackingService.GetTrackingDetails:output_type -> tracking.GetTrackingDetailsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tracking_tracking_proto_init() }
func file_tracking_tracking_proto_init() {
	if File_tracking_tracking_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tracking_tracking_proto_rawDesc), len(file_tracking_tracking_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tracking_tracking_proto_goTypes,
		DependencyIndexes: file_tracking_tracking_proto_depIdxs,
		MessageInfos:      file_tracking_tracking_proto_msgTypes,
	}.Build()
	File_tracking_tracking_proto = out.File
	file_tracking_tracking_proto_goTypes = nil
	file_tracking_tracking_proto_depIdxs = nil
}
